################################################################################
## Releasing the hounds in your local environment.
##
## Setup:
## $ gem install rubocop
##
## Run:
## $ rubocop ./path/to/file ./or/path/to/directory -c ./.hound.yml
##
################################################################################

################################################################################
##
## Custom options for Hydra::Works
## These options were plucked from below and modified accordingly.
##
################################################################################
AllCops:
  Include:
    - Rakefile
  Exclude:
    - db/**/*
    - config/**/*
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: false

MethodLength:
  Max: 10
  Description: 'Avoid methods longer than 10 lines of code.'
  CountComments: false
  Enabled: true

LineLength:
  Description: 'Limit lines to 140 characters.'
  Max: 140
  Enabled: true

AlignParameters:
  Description: >-
                 Align the parameters of a method call if they span more
                 than one line.
  Enabled: true

BlockComments:
  Description: 'Do not use block comments.'
  Enabled: true
  Exclude:
    - spec/spec_helper.rb

Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
  - spec/**/*
  - lib/**/version.rb

EmptyLinesAroundBlockBody:
  Enabled: false

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: trailing
  Enabled: true

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: true
  Max: 4

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()
  Enabled: true

RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: false

StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: true
  Exclude:
    - bin/*

HandleExceptions:
  Description: "Don't suppress exception."
  Enabled: true
  Exclude:
    - bin/*
